made changes in jenkinsfile

diff --git a/pipeline_3/Jenkinsfile b/pipeline_3/Jenkinsfile
--- a/pipeline_3/Jenkinsfile
+++ b/pipeline_3/Jenkinsfile
@@ -4,20 +4,16 @@ pipeline {
         AWS_REGION     = 'us-east-1'
         AWS_ACCOUNT_ID = '647800544853'
         ECR_REPO_NAME  = 'cicd-practice'
-        EC2_HOST       = '3.85.208.192'
+        EC2_HOST       = '13.221.131.107'
+        
         ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
         IMAGE_NAME   = "${ECR_REPO_NAME}"
         IMAGE_TAG    = "build-${env.BUILD_NUMBER}"
         FULL_IMAGE   = "${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
         LATEST_IMAGE = "${ECR_REGISTRY}/${IMAGE_NAME}:latest"
-    }
-
+}
     stages {
-        stage('Checkout') {
-            steps { checkout scm }
-        }
-
-        stage('AWS Login') {
+         stage('AWS Login') {
             steps {
                 withCredentials([usernamePassword(
                     credentialsId: 'aws-login-creds',
@@ -25,34 +21,39 @@ pipeline {
                     passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                 )]) {
                     sh '''
-                        set -e
                         export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                         export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                         export AWS_DEFAULT_REGION=${AWS_REGION}
-                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
+
+                        aws ecr get-login-password --region ${AWS_REGION} \
+                        | docker login --username AWS --password-stdin ${ECR_REGISTRY}
                     '''
                 }
             }
         }
-
-        stage('Build Image') {
+        stage('Build Docker Image') {
             steps {
-                dir('pipeline_3') {
-                    sh '''
-                        set -e
-                        docker build -t ${FULL_IMAGE} -t ${LATEST_IMAGE} .
-                    '''
-                }
+                sh '''
+                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
+                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${FULL_IMAGE}
+                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${LATEST_IMAGE}
+                '''
             }
         }
 
+        stage('Test Docker Image') {
+            steps {
+                sh '''
+                    docker run --rm ${FULL_IMAGE} curl -f http://localhost:8080/ || exit 1
+                '''
+            }
+        }
         stage('Push to ECR') {
             steps {
                 sh '''
-                    set -e
-                    docker push ${FULL_IMAGE}
-                    docker push ${LATEST_IMAGE}
-                '''
+                   docker push ${FULL_IMAGE}
+                   docker push ${LATEST_IMAGE}
+                ''' 
             }
         }
 
@@ -60,27 +61,37 @@ pipeline {
             steps {
                 withCredentials([sshUserPrivateKey(
                     credentialsId: 'ec2-ssh-key',
-                    keyFileVariable: 'SSH_KEY'
+                    keyFileVariable: 'SSH_KEY_PATH',
+                    usernameVariable: 'SSH_USER'
                 )]) {
-                    sh """
-                        set -e
-                        ssh -o StrictHostKeyChecking=no -i ${SSH_KEY} ec2-user@${EC2_HOST} '
-                            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
-                            docker pull ${LATEST_IMAGE}
-                            if [ \$(docker ps -q -f name=node-app | wc -l) -gt 0 ]; then
-                                docker stop node-app
-                                docker rm node-app
-                            fi
-                            docker run -d --name node-app -p 80:5000 ${LATEST_IMAGE}
-                        '
-                    """
+                    sh '''
+                        scp -i ${SSH_KEY_PATH} deploy.sh ${SSH_USER}@${EC2_HOST}:/tmp/
+                        ssh -i ${SSH_KEY_PATH} ${SSH_USER}@${EC2_HOST} 'bash /tmp/deploy.sh ${FULL_IMAGE}'
+                        aws ecr get-login-password --region ${AWS_REGION} \
+                        | docker login --username AWS --password-stdin ${ECR_REGISTRY}
+                        docker pull ${LATEST_IMAGE}
+                        if [ \$(docker ps -q -f name=cicd_practice | wc -l) -gt 0 ]; then
+                                docker stop cicd_practice
+                                docker rm cicd_practice
+                        fi
+                        docker run -d --name cicd_practice -p 5000:5000 ${FULL_IMAGE}
+                    '''
                 }
             }
         }
-    }
 
-    post {
-        success { echo "===== Deployment Finished Successfully =====" }
-        failure { echo "===== Deployment Failed =====" }
+        post {
+        success {
+            echo "===== Deployment Finished Successfully ====="
+        }
+        failure {
+            echo "===== Deployment Failed ====="
+        }
     }
+}
+    
+
+
+
+
 }
